# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e35b9418d0fae4282f590525e2c5a092800f3597a81238657f20596fa7463a1a1249c28e13ef25c8f36569200c7a38a2d95ce18cab2eb697a9bc5543dc554c1f

test:
  secret_key_base: 443249bb35143a879b948d2e77c3620d08eb800a2aa4244a822b277f9a1d229b5ad359644fad517d1b602a4461c6445998861bebfad4048350d445b32f323f8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
